/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 62
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_EQ = 3,
  sym_alpine_directive = 4,
  aux_sym_alpine_shorthand_token1 = 5,
  aux_sym_alpine_shorthand_token2 = 6,
  aux_sym_regular_attribute_name_token1 = 7,
  anon_sym_DQUOTE = 8,
  anon_sym_SQUOTE = 9,
  aux_sym_regular_attribute_value_token1 = 10,
  aux_sym_regular_attribute_value_token2 = 11,
  aux_sym_regular_attribute_value_token3 = 12,
  anon_sym_LBRACE = 13,
  anon_sym_COMMA = 14,
  anon_sym_RBRACE = 15,
  anon_sym_COLON = 16,
  sym_identifier = 17,
  sym_number = 18,
  anon_sym_PLUS_PLUS = 19,
  anon_sym_DASH_DASH = 20,
  anon_sym_LT_SLASH = 21,
  anon_sym_SLASH_GT = 22,
  sym_text = 23,
  sym_document = 24,
  sym_element = 25,
  sym_start_tag = 26,
  sym_attribute = 27,
  sym_alpine_attribute = 28,
  sym_regular_attribute = 29,
  sym_alpine_shorthand = 30,
  sym_regular_attribute_name = 31,
  sym_alpine_attribute_value = 32,
  sym_regular_attribute_value = 33,
  sym_alpine_expression = 34,
  sym_object_literal = 35,
  sym_object_property = 36,
  sym_string_literal = 37,
  sym_postfix_expression = 38,
  sym_end_tag = 39,
  sym_self_closing_tag = 40,
  sym_tag_name = 41,
  aux_sym_document_repeat1 = 42,
  aux_sym_start_tag_repeat1 = 43,
  aux_sym_object_literal_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_EQ] = "=",
  [sym_alpine_directive] = "alpine_directive",
  [aux_sym_alpine_shorthand_token1] = "alpine_shorthand_token1",
  [aux_sym_alpine_shorthand_token2] = "alpine_shorthand_token2",
  [aux_sym_regular_attribute_name_token1] = "regular_attribute_name_token1",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_regular_attribute_value_token1] = "regular_attribute_value_token1",
  [aux_sym_regular_attribute_value_token2] = "regular_attribute_value_token2",
  [aux_sym_regular_attribute_value_token3] = "regular_attribute_value_token3",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_attribute] = "attribute",
  [sym_alpine_attribute] = "alpine_attribute",
  [sym_regular_attribute] = "regular_attribute",
  [sym_alpine_shorthand] = "alpine_shorthand",
  [sym_regular_attribute_name] = "regular_attribute_name",
  [sym_alpine_attribute_value] = "alpine_attribute_value",
  [sym_regular_attribute_value] = "regular_attribute_value",
  [sym_alpine_expression] = "alpine_expression",
  [sym_object_literal] = "object_literal",
  [sym_object_property] = "object_property",
  [sym_string_literal] = "string_literal",
  [sym_postfix_expression] = "postfix_expression",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_tag_name] = "tag_name",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_object_literal_repeat1] = "object_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_alpine_directive] = sym_alpine_directive,
  [aux_sym_alpine_shorthand_token1] = aux_sym_alpine_shorthand_token1,
  [aux_sym_alpine_shorthand_token2] = aux_sym_alpine_shorthand_token2,
  [aux_sym_regular_attribute_name_token1] = aux_sym_regular_attribute_name_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_regular_attribute_value_token1] = aux_sym_regular_attribute_value_token1,
  [aux_sym_regular_attribute_value_token2] = aux_sym_regular_attribute_value_token2,
  [aux_sym_regular_attribute_value_token3] = aux_sym_regular_attribute_value_token3,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_attribute] = sym_attribute,
  [sym_alpine_attribute] = sym_alpine_attribute,
  [sym_regular_attribute] = sym_regular_attribute,
  [sym_alpine_shorthand] = sym_alpine_shorthand,
  [sym_regular_attribute_name] = sym_regular_attribute_name,
  [sym_alpine_attribute_value] = sym_alpine_attribute_value,
  [sym_regular_attribute_value] = sym_regular_attribute_value,
  [sym_alpine_expression] = sym_alpine_expression,
  [sym_object_literal] = sym_object_literal,
  [sym_object_property] = sym_object_property,
  [sym_string_literal] = sym_string_literal,
  [sym_postfix_expression] = sym_postfix_expression,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_tag_name] = sym_tag_name,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_object_literal_repeat1] = aux_sym_object_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_alpine_directive] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_alpine_shorthand_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_alpine_shorthand_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regular_attribute_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_regular_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regular_attribute_value_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_regular_attribute_value_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_alpine_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_alpine_shorthand] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_alpine_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_alpine_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_object_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_object_property] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_postfix_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 24,
        '\'', 25,
        '+', 3,
        ',', 32,
        '-', 4,
        '/', 6,
        ':', 34,
        '<', 13,
        '=', 15,
        '>', 14,
        '@', 8,
        '{', 31,
        '}', 33,
        '$', 35,
        '_', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead == '}') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\'') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(38);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ':') ADVANCE(9);
      if (lookahead == '=') ADVANCE(15);
      if (lookahead == '>') ADVANCE(14);
      if (lookahead == '@') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(40);
      END_STATE();
    case 7:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 8:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 9:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '<') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(39);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_alpine_directive);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_alpine_directive);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_alpine_shorthand_token1);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_alpine_shorthand_token2);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_regular_attribute_name_token1);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '$' ||
          lookahead == '_') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_regular_attribute_name_token1);
      if (lookahead == '-') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_regular_attribute_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_regular_attribute_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_regular_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_regular_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_regular_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_regular_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_regular_attribute_value_token3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 28},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 26},
  [54] = {.lex_state = 28},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 26},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_alpine_shorthand_token1] = ACTIONS(1),
    [aux_sym_regular_attribute_name_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(57),
    [sym_element] = STATE(9),
    [sym_start_tag] = STATE(5),
    [sym_self_closing_tag] = STATE(26),
    [aux_sym_document_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      anon_sym_GT,
    ACTIONS(11), 1,
      sym_alpine_directive,
    ACTIONS(15), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(17), 1,
      anon_sym_SLASH_GT,
    STATE(10), 1,
      sym_alpine_shorthand,
    STATE(12), 1,
      sym_regular_attribute_name,
    ACTIONS(13), 2,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
    STATE(4), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    STATE(14), 2,
      sym_alpine_attribute,
      sym_regular_attribute,
  [31] = 8,
    ACTIONS(21), 1,
      sym_alpine_directive,
    ACTIONS(27), 1,
      aux_sym_regular_attribute_name_token1,
    STATE(10), 1,
      sym_alpine_shorthand,
    STATE(12), 1,
      sym_regular_attribute_name,
    ACTIONS(19), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(24), 2,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
    STATE(3), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    STATE(14), 2,
      sym_alpine_attribute,
      sym_regular_attribute,
  [60] = 9,
    ACTIONS(11), 1,
      sym_alpine_directive,
    ACTIONS(15), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(30), 1,
      anon_sym_GT,
    ACTIONS(32), 1,
      anon_sym_SLASH_GT,
    STATE(10), 1,
      sym_alpine_shorthand,
    STATE(12), 1,
      sym_regular_attribute_name,
    ACTIONS(13), 2,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
    STATE(3), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    STATE(14), 2,
      sym_alpine_attribute,
      sym_regular_attribute,
  [91] = 7,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(34), 1,
      anon_sym_LT_SLASH,
    ACTIONS(36), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(26), 1,
      sym_self_closing_tag,
    STATE(27), 1,
      sym_end_tag,
    STATE(7), 2,
      sym_element,
      aux_sym_document_repeat1,
  [114] = 7,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      anon_sym_LT,
    ACTIONS(43), 1,
      anon_sym_LT_SLASH,
    ACTIONS(45), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(26), 1,
      sym_self_closing_tag,
    STATE(6), 2,
      sym_element,
      aux_sym_document_repeat1,
  [137] = 7,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(34), 1,
      anon_sym_LT_SLASH,
    ACTIONS(48), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(23), 1,
      sym_end_tag,
    STATE(26), 1,
      sym_self_closing_tag,
    STATE(6), 2,
      sym_element,
      aux_sym_document_repeat1,
  [160] = 2,
    ACTIONS(52), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(50), 6,
      anon_sym_GT,
      anon_sym_EQ,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [172] = 6,
    ACTIONS(5), 1,
      anon_sym_LT,
    ACTIONS(48), 1,
      sym_text,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_start_tag,
    STATE(26), 1,
      sym_self_closing_tag,
    STATE(6), 2,
      sym_element,
      aux_sym_document_repeat1,
  [192] = 3,
    ACTIONS(58), 1,
      anon_sym_EQ,
    ACTIONS(60), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(56), 5,
      anon_sym_GT,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [206] = 2,
    ACTIONS(64), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(62), 6,
      anon_sym_GT,
      anon_sym_EQ,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [218] = 3,
    ACTIONS(68), 1,
      anon_sym_EQ,
    ACTIONS(70), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(66), 5,
      anon_sym_GT,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [232] = 2,
    ACTIONS(74), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(72), 5,
      anon_sym_GT,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [243] = 2,
    ACTIONS(78), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(76), 5,
      anon_sym_GT,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [254] = 2,
    ACTIONS(82), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(80), 5,
      anon_sym_GT,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [265] = 2,
    ACTIONS(86), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(84), 5,
      anon_sym_GT,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [276] = 2,
    ACTIONS(90), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(88), 5,
      anon_sym_GT,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [287] = 2,
    ACTIONS(94), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(92), 5,
      anon_sym_GT,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [298] = 2,
    ACTIONS(98), 1,
      aux_sym_regular_attribute_name_token1,
    ACTIONS(96), 5,
      anon_sym_GT,
      sym_alpine_directive,
      aux_sym_alpine_shorthand_token1,
      aux_sym_alpine_shorthand_token2,
      anon_sym_SLASH_GT,
  [309] = 4,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    ACTIONS(102), 1,
      anon_sym_SQUOTE,
    STATE(44), 1,
      sym_string_literal,
    ACTIONS(104), 2,
      sym_identifier,
      sym_number,
  [323] = 4,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(58), 1,
      sym_alpine_expression,
    STATE(47), 2,
      sym_object_literal,
      sym_postfix_expression,
  [337] = 4,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      sym_identifier,
    STATE(55), 1,
      sym_alpine_expression,
    STATE(47), 2,
      sym_object_literal,
      sym_postfix_expression,
  [351] = 2,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(112), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [360] = 4,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      anon_sym_SQUOTE,
    ACTIONS(118), 1,
      aux_sym_regular_attribute_value_token3,
    STATE(17), 1,
      sym_regular_attribute_value,
  [373] = 2,
    ACTIONS(120), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(122), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [382] = 2,
    ACTIONS(124), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(126), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [391] = 2,
    ACTIONS(128), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(130), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [400] = 2,
    ACTIONS(132), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(134), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [409] = 2,
    ACTIONS(136), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(138), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [418] = 2,
    ACTIONS(140), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    ACTIONS(142), 2,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH_DASH,
  [427] = 3,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(146), 1,
      anon_sym_SQUOTE,
    STATE(15), 1,
      sym_alpine_attribute_value,
  [437] = 3,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
    ACTIONS(150), 1,
      sym_identifier,
    STATE(36), 1,
      sym_object_property,
  [447] = 2,
    ACTIONS(154), 1,
      sym_text,
    ACTIONS(152), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [455] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      aux_sym_object_literal_repeat1,
  [465] = 3,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      aux_sym_object_literal_repeat1,
  [475] = 3,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    STATE(35), 1,
      aux_sym_object_literal_repeat1,
  [485] = 2,
    ACTIONS(169), 1,
      sym_text,
    ACTIONS(167), 2,
      anon_sym_LT,
      anon_sym_LT_SLASH,
  [493] = 2,
    ACTIONS(171), 1,
      aux_sym_regular_attribute_name_token1,
    STATE(61), 1,
      sym_tag_name,
  [500] = 1,
    ACTIONS(173), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [505] = 2,
    ACTIONS(171), 1,
      aux_sym_regular_attribute_name_token1,
    STATE(2), 1,
      sym_tag_name,
  [512] = 1,
    ACTIONS(175), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [517] = 1,
    ACTIONS(177), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [522] = 2,
    ACTIONS(150), 1,
      sym_identifier,
    STATE(45), 1,
      sym_object_property,
  [529] = 1,
    ACTIONS(179), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [534] = 1,
    ACTIONS(159), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [539] = 1,
    ACTIONS(181), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [544] = 1,
    ACTIONS(140), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [549] = 1,
    ACTIONS(183), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [554] = 1,
    ACTIONS(185), 1,
      anon_sym_DQUOTE,
  [558] = 1,
    ACTIONS(185), 1,
      anon_sym_SQUOTE,
  [562] = 1,
    ACTIONS(187), 1,
      aux_sym_regular_attribute_value_token2,
  [566] = 1,
    ACTIONS(189), 1,
      anon_sym_COLON,
  [570] = 1,
    ACTIONS(191), 1,
      aux_sym_regular_attribute_value_token1,
  [574] = 1,
    ACTIONS(193), 1,
      aux_sym_regular_attribute_value_token2,
  [578] = 1,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
  [582] = 1,
    ACTIONS(197), 1,
      aux_sym_regular_attribute_value_token1,
  [586] = 1,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
  [590] = 1,
    ACTIONS(195), 1,
      anon_sym_SQUOTE,
  [594] = 1,
    ACTIONS(201), 1,
      anon_sym_DQUOTE,
  [598] = 1,
    ACTIONS(201), 1,
      anon_sym_SQUOTE,
  [602] = 1,
    ACTIONS(203), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 91,
  [SMALL_STATE(6)] = 114,
  [SMALL_STATE(7)] = 137,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 172,
  [SMALL_STATE(10)] = 192,
  [SMALL_STATE(11)] = 206,
  [SMALL_STATE(12)] = 218,
  [SMALL_STATE(13)] = 232,
  [SMALL_STATE(14)] = 243,
  [SMALL_STATE(15)] = 254,
  [SMALL_STATE(16)] = 265,
  [SMALL_STATE(17)] = 276,
  [SMALL_STATE(18)] = 287,
  [SMALL_STATE(19)] = 298,
  [SMALL_STATE(20)] = 309,
  [SMALL_STATE(21)] = 323,
  [SMALL_STATE(22)] = 337,
  [SMALL_STATE(23)] = 351,
  [SMALL_STATE(24)] = 360,
  [SMALL_STATE(25)] = 373,
  [SMALL_STATE(26)] = 382,
  [SMALL_STATE(27)] = 391,
  [SMALL_STATE(28)] = 400,
  [SMALL_STATE(29)] = 409,
  [SMALL_STATE(30)] = 418,
  [SMALL_STATE(31)] = 427,
  [SMALL_STATE(32)] = 437,
  [SMALL_STATE(33)] = 447,
  [SMALL_STATE(34)] = 455,
  [SMALL_STATE(35)] = 465,
  [SMALL_STATE(36)] = 475,
  [SMALL_STATE(37)] = 485,
  [SMALL_STATE(38)] = 493,
  [SMALL_STATE(39)] = 500,
  [SMALL_STATE(40)] = 505,
  [SMALL_STATE(41)] = 512,
  [SMALL_STATE(42)] = 517,
  [SMALL_STATE(43)] = 522,
  [SMALL_STATE(44)] = 529,
  [SMALL_STATE(45)] = 534,
  [SMALL_STATE(46)] = 539,
  [SMALL_STATE(47)] = 544,
  [SMALL_STATE(48)] = 549,
  [SMALL_STATE(49)] = 554,
  [SMALL_STATE(50)] = 558,
  [SMALL_STATE(51)] = 562,
  [SMALL_STATE(52)] = 566,
  [SMALL_STATE(53)] = 570,
  [SMALL_STATE(54)] = 574,
  [SMALL_STATE(55)] = 578,
  [SMALL_STATE(56)] = 582,
  [SMALL_STATE(57)] = 586,
  [SMALL_STATE(58)] = 590,
  [SMALL_STATE(59)] = 594,
  [SMALL_STATE(60)] = 598,
  [SMALL_STATE(61)] = 602,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alpine_shorthand, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alpine_shorthand, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alpine_attribute, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alpine_attribute, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_attribute_name, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_attribute_name, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_attribute, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_attribute, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_name, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alpine_attribute, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alpine_attribute, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_attribute_value, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_attribute_value, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_attribute, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_attribute, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alpine_attribute_value, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_alpine_attribute_value, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_attribute_value, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_regular_attribute_value, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alpine_expression, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_literal_repeat1, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_postfix_expression, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_literal, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_literal, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_property, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_literal, 4, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [199] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_alpinejs(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "alpinejs",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
